### ISSUE TITLE
Missing .gitignore

### ISSUE THREAD

**Issue by mcaulifn** [wulfmann/aws-cloudformation-rpdk-python-plugin#1]
gitignore template appears to be missing

```
[2019-11-19T20:08:02Z] DEBUG    - Logging set up successfully
[2019-11-19T20:08:02Z] DEBUG    - Running init: Namespace(command=<function init at 0x7f493ec768c0>, force=False, subparser_name='init', verbose=0, version=False)
[2019-11-19T20:08:02Z] DEBUG    - Root directory: /c/Users/nmcauliffe/repos/app-rpdk
[2019-11-19T20:08:02Z] WARNING  - Initializing new project
[2019-11-19T20:08:02Z] DEBUG    - Loading project file '/c/Users/nmcauliffe/repos/app-rpdk/.rpdk-config'
[2019-11-19T20:08:09Z] DEBUG    - Resource type identifier: org::org::app
[2019-11-19T20:08:09Z] WARNING  - One language plugin found, defaulting to python
[2019-11-19T20:08:09Z] DEBUG    - Language plugin: python
[2019-11-19T20:08:09Z] DEBUG    - Init started
[2019-11-19T20:08:09Z] DEBUG    - Writing .gitignore: /c/Users/nmcauliffe/repos/app-rpdk/.gitignore
[2019-11-19T20:08:09Z] DEBUG    - Unhandled exception
Traceback (most recent call last):
  File "/c/Users/nmcauliffe/repos/app-rpdk/.env/lib/python3.7/site-packages/rpdk/core/cli.py", line 98, in main
    args.command(args)
  File "/c/Users/nmcauliffe/repos/app-rpdk/.env/lib/python3.7/site-packages/rpdk/core/init.py", line 153, in wrapper
    function(args)
  File "/c/Users/nmcauliffe/repos/app-rpdk/.env/lib/python3.7/site-packages/rpdk/core/init.py", line 143, in init
    project.init(type_name, language)
  File "/c/Users/nmcauliffe/repos/app-rpdk/.env/lib/python3.7/site-packages/rpdk/core/project.py", line 181, in init
   self._plugin.init(self)
  File "/c/Users/nmcauliffe/repos/app-rpdk/.env/lib/python3.7/site-packages/rpdk/python/codegen.py", line 52, in init
    contents = resource_stream(__name__, "data/python.gitignore").read()
  File "/c/Users/nmcauliffe/repos/app-rpdk/.env/lib/python3.7/site-packages/rpdk/core/data_loaders.py", line 32, in resource_stream
    f = pkg_resources.resource_stream(package_name, resource_name)
  File "/c/Users/nmcauliffe/repos/app-rpdk/.env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1151, in resource_stream
    self, resource_name
  File "/c/Users/nmcauliffe/repos/app-rpdk/.env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1584, in get_resource_stream
    return open(self._fn(self.module_path, resource_name), 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/c/Users/nmcauliffe/repos/app-rpdk/.env/lib/python3.7/site-packages/rpdk/python/data/python.gitignore'
```

**Comment by wulfmann** [comment]
@mcaulifn this should be fixed in the latest version.
